### ISSUE TITLE
Telify plugin source code

### ISSUE THREAD

**Issue by Jaminy** [Jaminy/GSoC#12]
For scanning telephone number in the message, should it scan for numbers in the message or the message starts with tel. ?

**Comment by irl** [comment]
Scan the body of the message for things that look like phone numbers. Phone numbers are unlikely to be in the headers, I'm not aware of any standards for adding phone numbers there.

**Comment by Jaminy** [comment]
What if there are numbers which are not phone numbers?Wouldn't be added as phone number?

**Comment by irl** [comment]
Some phone numbers will be easy to recognise because they'll be a + followed by more than 7 or so numbers. Some will be harder, but it's a good bet that with less than 7 numbers it's probably not a phone number.

You can validate further by using the phonenumbers library. Start by doing .parse() and then you can use the phonenumbers.is_valid_number() function to check if it's a valid number.
